### ISSUE TITLE
Over-minified Image Problem

### ISSUE THREAD

**Issue by pourmand1376** [kitabisa/docker-slim-action#4]
Hi, Thanks for building this amazing Github action. 

I want to add your workflow to [al-folio github template](https://github.com/alshedivat/al-folio). 

This is my docker-compose file:
```
version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
```

This is my github actions file:
```
name: Docker Slim

#Only trigger, when the build workflow succeeded
# on:
#   workflow_run:
#     workflows: ["Docker Image CI"]
#     types:
#       - completed

on: 
  push:
    branches: 
      - '**'

jobs: 
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: update docker-compose
      shell: bash
      run:  |
        sed -i "s|\.:|${{ github.workspace }}:|g" ${{ github.workspace }}/docker-compose.yml 
        cat ${{ github.workspace }}/docker-compose.yml 
        
    - uses: kitabisa/docker-slim-action@v1
      env:
        DSLIM_HTTP_PROBE: false
        DSLIM_PULL: true
        DSLIM_COMPOSE_FILE: ${{ github.workspace }}/docker-compose.yml
        DSLIM_TARGET_COMPOSE_SVC: jekyll
      with:
        target: amirpourmand/al-folio
        tag: "slim"
```

I've noticed that when I use Docker Slim, the image size on my local machine is reduced from 1.6GB to 188MB, which is already impressive. However, when I utilize Docker Slim within my GitHub Actions workflow, the image size is further reduced to just 14MB, which seems almost impossible. 

I can not understand where the problem is or how I should fix this.

[Here](https://github.com/pourmand1376/pourmand1376.github.io/actions/runs/6063524246/job/16450980625) you can see the complete log file.
